In [1]:
import numpy as np
print(np.__version__)

1.26.4

In [2]:
import pandas as pd

In [3]:
import sys, numpy as np, pandas as pd
print("Python:", sys.version)
print("NumPy :", np.__version__)
print("pandas:", pd.__version__)

Python: 3.11.14 | packaged by conda-forge | (main, Oct 22 2025, 22:56:31) [Clang 19.1.7 ]
NumPy : 1.26.4
pandas: 2.3.3

In [8]:
df = pd.read_excel('Option Chain.xlsx')

In [9]:
df.head()

,Unnamed: 0,Unnamed: 1,Type,ID_BB_SEC_NUM_DES,Mid Price,Delta,Gamma,Vega,Theta,IV
0,05/09/25,NaN,Put,SPY 05/09/25 P335,0.38,-0.009,0.0011,0.038,-0.0459,76.142
1,SPY 05/09/25 P325,NaN,Put,SPY 05/09/25 P325,0.35,-0.008,0.0009,0.033,-0.0412,78.878
2,SPY 05/09/25 P315,NaN,Put,SPY 05/09/25 P315,0.35,-0.006,0.0008,0.028,-0.0358,81.263
3,SPY 05/09/25 P305,NaN,Put,SPY 05/09/25 P305,0.31,-0.005,0.0006,0.024,-0.0317,83.962
4,SPY 05/09/25 P330,NaN,Put,SPY 05/09/25 P330,0.47,-0.008,0.0010,0.035,-0.0426,77.245

In [10]:
pattern = r'^(?P<ticker>[A-Za-z]+)\s+(?P<expiry>\d{2}/\d{2}/\d{2})\s+(?P<option_type>[cCpP])(?P<strike>\d+\.?\d*)'

In [12]:
parsed = df["ID_BB_SEC_NUM_DES"].str.extract(pattern)

In [13]:
parsed["option_type"] = parsed["option_type"].str.upper()
parsed["strike"] = parsed["strike"].astype(float)

In [14]:
parsed

    ticker    expiry option_type  strike
0      SPY  05/09/25           P   335.0
1      SPY  05/09/25           P   325.0
2      SPY  05/09/25           P   315.0
3      SPY  05/09/25           P   305.0
4      SPY  05/09/25           P   330.0
..     ...       ...         ...     ...
226    SPY  05/09/25           C   600.0
227    SPY  05/09/25           C   545.0
228    SPY  05/09/25           C   562.0
229    SPY  05/09/25           C   590.0
230    SPY  05/09/25           C   572.0

[231 rows x 4 columns]

In [15]:
df = pd.concat([df, parsed], axis=1)

In [17]:
df.head(10)

,Unnamed: 0,Unnamed: 1,Type,ID_BB_SEC_NUM_DES,Mid Price,Delta,Gamma,Vega,Theta,IV,ticker,expiry,option_type,strike
0,05/09/25,NaN,Put,SPY 05/09/25 P335,0.38,-0.009,0.0011,0.038,-0.0459,76.142,SPY,05/09/25,P,335.0
1,SPY 05/09/25 P325,NaN,Put,SPY 05/09/25 P325,0.35,-0.008,0.0009,0.033,-0.0412,78.878,SPY,05/09/25,P,325.0
2,SPY 05/09/25 P315,NaN,Put,SPY 05/09/25 P315,0.35,-0.006,0.0008,0.028,-0.0358,81.263,SPY,05/09/25,P,315.0
3,SPY 05/09/25 P305,NaN,Put,SPY 05/09/25 P305,0.31,-0.005,0.0006,0.024,-0.0317,83.962,SPY,05/09/25,P,305.0
4,SPY 05/09/25 P330,NaN,Put,SPY 05/09/25 P330,0.47,-0.008,0.0010,0.035,-0.0426,77.245,SPY,05/09/25,P,330.0
5,SPY 05/09/25 P370,NaN,Put,SPY 05/09/25 P370,0.81,-0.017,0.0021,0.066,-0.0713,67.877,SPY,05/09/25,P,370.0
6,SPY 05/09/25 P355,NaN,Put,SPY 05/09/25 P355,0.61,-0.013,0.0016,0.052,-0.0595,71.412,SPY,05/09/25,P,355.0
7,SPY 05/09/25 P365,NaN,Put,SPY 05/09/25 P365,0.70,-0.015,0.0019,0.061,-0.0671,69.036,SPY,05/09/25,P,365.0
8,SPY 05/09/25 P300,NaN,Put,SPY 05/09/25 P300,0.18,-0.005,0.0006,0.022,-0.0295,85.236,SPY,05/09/25,P,300.0
9,SPY 05/09/25 C305,NaN,Call,SPY 05/09/25 C305,195.95,1.000,NaN,NaN,NaN,NaN,SPY,05/09/25,C,305.0

In [18]:
df.to_excel("options_parsed.xlsx", index=False)